name: Deployment
# on:
#   push:
#     tags:
#       - '*'

on: 
  push:
    # only trigger on branches, not on tags
    branches: 'main'

env:
  LOG_LEVEL: DEBUG

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy new Homebrew formula
        run: ./deployment.py