# name: Deployment
# on:
#   push:
#     tags:
#       - '*'

on: 
  push:
    # only trigger on branches, not on tags
    branches: 'main'

env:
  LOG_LEVEL: DEBUG
  GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
  TARGET_REPO_NAME: danibachar/HomebrewAutoDeplyment
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy new Homebrew formula
        run: ./make/tasks/homebrew/deploy.sh
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1