name: Deployment
on:
  push:
    tags:
      - '*'

env:
  LOG_LEVEL: DEBUG

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy new Homebrew formula
        run: ./deployment.py