name: Deployment
# on:
#   push:
#     tags:
#       - '*'

on: 
  push:
    # only trigger on branches, not on tags
    branches: 'main'

env:
  LOG_LEVEL: DEBUG
  DANIEL_GITHUB_ACCESS_TOKEN: ${{ secrets.DANIEL_GITHUB_ACCESS_TOKEN }}
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dependencies
        run: pip install -r requirements.txt
      - name: Deploy new Homebrew formula
        run: python -u deployment.py