name: Deployment
on:
  push:
    tags:
      - '*'

env:
  LOG_LEVEL: DEBUG
  DANIEL_GITHUB_ACCESS_TOKEN: ${{ secrets.DANIEL_GITHUB_ACCESS_TOKEN }}
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dependencies
        run: pip3 install -r requirements.txt
      - name: Deploy new Homebrew formula
        run: python3 -u deployment.py